### ISSUE TITLE
NWS forecast API failures break climate extremes tool

### ISSUE THREAD

**Issue by clhenrick** [berkeley-gif/caladapt-website-2021#1]
When the API call to `api.weather.gov` fails, the missing data value breaks [tools/climate-extremes](https://dev.cal-adapt.org/tools/climate-extremes/).

The failure should only cause the "near term forecast" feature to not load / show data and shouldn't prevent "historical observations" or "future climate projections" from functioning, assuming that they don't rely on data from `api.weather.gov`.

**Comment by clhenrick** [comment]
If the NWS forecast API ends up being flakey on a regular basis we might consider switching to a similar weather forecast API from another provider such as [OpenWeatherMap](https://openweathermap.org/forecast5).

**Comment by clhenrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Safe guards for NWS API flakiness](https://trello.com/c/gASTzuCW/9-safe-guards-for-nws-api-flakiness)

**Comment by mukhtyar** [comment]
Separated forecast request into a separate step, and added an error message for user to try again in a few minutes if unable to fetch data. Not being able to connect to NWS should not break functionality in rest of the tool. Via https://github.com/berkeley-gif/caladapt-website-2021/pull/9
