### ISSUE TITLE
Update copyright year in footer

### ISSUE THREAD

**Issue by mukhtyar** [berkeley-gif/caladapt-website-2021#253]
The year is still 2021 in the footer Copyright text

**Comment by elehmer** [comment]
> The year is still 2021 in the footer Copyright text

Check, will update...

**Comment by elehmer** [comment]
#254

**Comment by elehmer** [comment]
> > The year is still 2021 in the footer Copyright text
> 
> Check, will update...

PR #254

**Comment by elehmer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update copyright date in footer](https://trello.com/c/lnVDTvLy/213-update-copyright-date-in-footer)

**Comment by elehmer** [comment]
> > > The year is still 2021 in the footer Copyright text
> > 
> > 
> > Check, will update...
> 
> PR #254

Done and deployed to production and dev
