### ISSUE TITLE
Browser navigation broken on Extreme Weather tool

### ISSUE THREAD

**Issue by clhenrick** [berkeley-gif/caladapt-website-2021#5]
When navigating to the page for the Extreme Weather tool, hitting the browser's back button causes the URL to change but the previous page's content doesn't load.

**Comment by clhenrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Browser navigation broken on Extreme Weather tool](https://trello.com/c/zwhfooYH/30-browser-navigation-broken-on-extreme-weather-tool)

**Comment by mukhtyar** [comment]
This was caused by MapBox not finding the map's `Style` object during `onDestroy` in the `VectorLayer` component. Fixed by adding a `getStyle()` check in https://github.com/berkeley-gif/caladapt-website-2021/pull/15
