### ISSUE TITLE
Clearing model selection after fetching data breaks app

### ISSUE THREAD

**Issue by clhenrick** [berkeley-gif/caladapt-website-2021#7]
On the Annual Averages tool, if I fetch data for a location then clear the existing selected models, the UI enters a loading state which it doesn't recover from, perhaps from a network request failure to Cal Adapt API:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/161748/128256815-1730d93b-b44a-4157-a2e4-0e414edf0ba1.png">

**Comment by clhenrick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clearing model selection in settings breaks the Annual Averages tool](https://trello.com/c/vP2az7mE/58-clearing-model-selection-in-settings-breaks-the-annual-averages-tool)

**Comment by mukhtyar** [comment]
Fixed with pull request
